Enhancement: Add comment-changes workflow
fox0430/moe pull request #1723
Opened 2023-05-22 21:58 UTC by fox0430

Close #1722

2023-05-23 14:42 UTC, kevinmatthes reviewed
I added some comments on the new features I implemented into Aeruginous; you can now create links within the resulting fragment!  I also added the semantics to query the PR number.

Please check whether these suggestions would work for you.

2023-05-23 14:42 UTC, kevinmatthes commented on .github/workflows/comment-changes.yml
> +      - name: Install nightly toolchain
Hosted GitHub Action workflow runners are shipped with Rust installed; in fact, they even have GCC and the GNU Fortran compiler installed.  Thus, this step can be abbreviated to a simple `rustup update` because

- `rustup` is already installed on the runner.
- Aeruginous does not require Nightly Rust, Rust Stable suffices.

However, Aeruginous always requires the latest available version of Rust Stable due to requiring the access to the very latest features of Rust to offer all configured modes.  During the development, I noticed that the GitHub hosted runners have a delay of about one week before applying the very latest Rust toolchain version.  Hence, a call to `rustup update` is definitely required as the Aeruginous repository automatically upgrades its required version of Rust once per week.

2023-05-23 14:42 UTC, kevinmatthes commented on changelog.d/20230522_220116_GitHub_Actions_add-aeruginous-workflow.rst
This fragment can be deleted due to not matching the Scriv settings; "Enhancement" is not configured to be a CHANGELOG category, yet.  Some hours ago, I implemented the functionality to create links such that you can run the following commands to receive a perfect Scriv fragment:

```bash
git commit --allow-empty -m 'Added: `#1723`_ comment-changes workflow; fixes `#1722`_'
aeruginous comment-changes -d : -n 1 -o changelog.d/ -l \#1722 -t https://github.com/fox0430/moe/issues/1722 -l \#1723 -t https://github.com/fox0430/moe/pull/1723
git push
```

The new options `-l` and `-t` represent `--link` and `--target`, respectively, such that you can define custom links in the fragment.  As you can see, you are allowed to define multiple links that way; the first given link name will be associated with the first given link target, the second name with the second target, and so on.  If there should be more link names than targets or vice versa, the arguments which cannot be associated anymore will be ignored silently.  (Or should I make Aeruginous print a warning, then?)

Please note that this will create an empty commit, i.e., it will not contain any changes.  You can also name some change to this branch with the above commit message and run Aeruginous on it to achieve the same result.

2023-05-23 14:42 UTC, kevinmatthes commented on changelog.d/20230523_065316_shuu.n_add_aeruginous_workflow.rst
Please see my comment from above to create a smaller fragment with the very same effect.

2023-05-23 14:42 UTC, kevinmatthes commented on .github/workflows/comment-changes.yml
> +          aeruginous comment-changes -d ':' -n 1 -o changelog.d/
I finally found out how to get the PR number, even *without* having to call any Action!

```bash
aeruginous comment-changes -d : -n 1 -o changelog.d/ -l ${{ github.event.pull_request.number }} -t https://github.com/fox0430/moe/pull/${{ github.event.pull_request.number }}
```

2023-05-23 19:02 UTC, kevinmatthes commented
@fox0430

Aeruginous v1.1.0 is released! :tada:

This means that you can fetch the application from the Rust registry as a stable binary by calling `cargo install aeruginous`.  If there should be changes to the calling semantics in future versions, I will let you know such that the workflow will not break.

2023-05-24 15:24 UTC, kevinmatthes requested changes
@fox0430

The workflow is perfect, now!

As a last step, I would like to ask to you to create an *empty* commit on this branch using the following command.

```bash
git commit --allow-empty -m 'Added: `#1723`_ comment-changes workflow; fixes `#1722`_'
```

Then, please go the Actions tab on the GitHub website and manually trigger the `comment-changes` workflow on this branch.  This will be the final test for the workflow before it will be applied in production.

2023-05-24 16:10 UTC, fox0430 commented
@avahe-kellenberger 

I can not trigger the workflow... Do you know how to trigger it before merging? Do I need to reopen this PR..?

2023-05-24 17:05 UTC, kevinmatthes commented
@fox0430

The easiest would be to:

1. add `reopened` as trigger condition between line 25 and 26 in the workflow file and commit this change with the message ```Added: `#1723`_ comment-changes workflow```.
2. close this PR.
3. reopen this PR.
4. wait for the workflow to succeed before removing the trigger condition `reopened` in the workflow file, again.

This should solve the problem.

2023-05-24 17:28 UTC, kevinmatthes requested changes
Wonderful!

There is one more thing left regarding the rendered fragment; see below.  Please change this last detail and I will give my approval to this PR.

I would like to suggest to leave the alternative trigger condition of the workflow in; it might be useful in the future.

2023-05-24 17:28 UTC, kevinmatthes commented on changelog.d/20230524_171657_GitHub_Actions_add-aeruginous-workflow.rst
You could either add the link to the issue or remove the part ```; fixes `#1722`_```.  I would recommend the latter option as the workflow by default will only create links to the PR.  GitHub will take care about metadata annotation by mentioning the PR number, so it will be implicitly clear to visitors that this PR is related to #1722 as this is outlined in the PR's opening comment.

2023-05-24 17:42 UTC, fox0430 commented on changelog.d/20230524_171657_GitHub_Actions_add-aeruginous-workflow.rst
@kevinmatthes 

Okay, I remove it. But is it impossible to create an issue link? I want to use commit messages like this `Fix #xxx; description`.

2023-05-24 18:03 UTC, kevinmatthes commented on changelog.d/20230524_171657_GitHub_Actions_add-aeruginous-workflow.rst
@fox0430

It is not completely impossible but difficult.  You would need to extract the issue number from the commit message and pass it to Aeruginous.  This is dangerous as it would allow for code injection.

Aeruginous itself allows for the linking to issues but we would need to implement this into the workflow somehow.  I will keep looking for a solution to this.  For now, I would like to suggest to merge the current design of the workflow as a basic setup for further adjustments later on.

2023-05-24 19:20 UTC, fox0430 commented on changelog.d/20230524_171657_GitHub_Actions_add-aeruginous-workflow.rst
@kevinmatthes 

Okay, Thank you for your suggestion and support!

2023-05-24 19:23 UTC, kevinmatthes approved these changes

2023-05-24 19:25 UTC, merged